### ISSUE TITLE
Is the word neww a typo?

### ISSUE THREAD

**Issue by craigappl** [terraframe/common-geo-registry-adapter#1]
Please review the following line of code and identify if the variable neww is a typo.

https://github.com/terraframe/common-geo-registry-adapter/blob/29541ae11ff4a2976ab7c3f3379af97b2cb8677f/java/common/src/main/java/org/commongeoregistry/adapter/constants/DefaultTerms.java#L17

**Comment by justinlewis** [comment]
Attentive you are.   - Yoda

No it's not a typo. "new" is a reserved keyword in Java.  Thanks for looking close though!
