### ISSUE TITLE
Trying to get all children of a geo-object without specifying the children types throws an exception

### ISSUE THREAD

**Issue by ekigamba** [terraframe/common-geo-registry-adapter#13]
On the CGR API, one can fetch the children of a geo-object without specifying the children types. I think this is the correct call for getting children from the provided instructions https://cgr-domain.com/cgr/geoobject/getchildren?parentId=411744d7-3e21-4096-87ae-0000002d0873&parentTypeCode=Cambodia_Province&recursive=true&childrenType=[]

On the CGR Adapter, I get an exception whenever I pass a null or empty string array for the children types.

@justinlewis What do you think?

**Comment by rrowlands** [comment]
I added support to the API for null and empty strings for getChildGeoObjects and getParentGeoObjects. A corner case (which does not work) is leaf nodes. You must provide the GeoObjectType information if you want to fetch leaf nodes. Finally, the registry provides a method 'geoobjecttype/get-all'. The parameter is optional, and if omitted it will return all of them. You may also invoke 'geoobjecttype/get-all' and can provide the 'includeLeafTypes' boolean parameter. I will update the documentation for all this very soon.
