### ISSUE TITLE
Making API requests with the CGR adapter reduces the cached IDs

### ISSUE THREAD

**Issue by ekigamba** [terraframe/common-geo-registry-adapter#14]
Making API requests on the Android geo-registry adapter tends to reduce the cached IDs
If I populate the ID service with a small amount of IDs and make requests in which the geo-objects are more than the cached IDs, I get an `EmptyCacheIDException`

In my case, I keep on running into EmptyCacheIDException whenever getting children of a parent geo-object. It would be difficult to tell how many IDs are required if this were the case (where for every entity queried we require a cached ID)

**Comment by rrowlands** [comment]
This will be included in 0.4.0.
