### ISSUE TITLE
getChildGeoObjects not returning geometries

### ISSUE THREAD

**Issue by rrowlands** [terraframe/common-geo-registry-adapter#18]
Ephraim has invoked getChildGeoObjects on Cambodia and the children did not have geometries.

**Comment by rrowlands** [comment]
[geojson.txt](https://github.com/terraframe/common-geo-registry-adapter/files/3233135/geojson.txt)

**Comment by rrowlands** [comment]
Some of them have geometries and some do not.

**Comment by jsmethie** [comment]
It is possible for Geo Objects to not have any geometries specified.  I verified on the server that the children in the geojson.txt without geometries also do not have geometries on the server.  So I believe this is working as intended.
