### ISSUE TITLE
Persist last push id only after a successful push to server

### ISSUE THREAD

**Issue by ekigamba** [terraframe/common-geo-registry-adapter#5]
The strategy used for `AndroidRegistryClient.pushObjectsToRegistry` or better yet `LocalObjectCache.getUnpushedActionHistory` assumes that all post requests will be successful and therefore updates the last push id as soon as we fetch all unsynced actions from local db. The call should do just retrieve unpushed action history. 

We should also allow for fetching unpushed action history to a certain limit, so that client apps can be able to manage pushes in situations where network connection might not be as reliable and fast

**Comment by rrowlands** [comment]
This issue should be fixed in our latest 0.3.0 release. Please re-test and I will close the ticket if your issue is resolved.
