### ISSUE TITLE
Need the ability to delete GeoObjects.

### ISSUE THREAD

**Issue by justinlewis** [terraframe/common-geo-registry-adapter#6]
Currently I cannot find a API call on the android /java adapter for deleting geo-objects or querying. I also cannot find one in the API documentation. This is important especially for just locations. I understand this means a lot of decision making for already related objects (Objects that already have relations such as being parents, children or being used in hierarchy definition)

This content was provided by Ona in a conversation and copied here by @justinlewis

**Comment by justinlewis** [comment]
Comments from @nmceachen - Since there can be dependencies on an object, we decided not to allow deletes but rather set the status to inactive. However, as we prepare for the Governance use cases we think we can support deletes for objects that have not yet been incorporated into a master list. However, once made a part of the master list then we don’t think it should be deleted.

**Comment by justinlewis** [comment]
Comments from @nmceachen - What about a new object that is created offline in the client side and we have a reference to the object that was created? If a location has been rejected for a reason we may need a global policy for mapping or merging geoObjects. This is an ongoing conversation for the CGR.

**Comment by rrowlands** [comment]
We are not supporting deletes anytime in the near future.
