### ISSUE TITLE
Support for querying metadata and updating a cache relative to the current state in the app

### ISSUE THREAD

**Issue by justinlewis** [terraframe/common-geo-registry-adapter#7]
The adapter needs to keep track of currently synced metadata and only perform updates compared to the current strategy where you need to refetch all metadata again. At some point all these metadata will be a lot when the service goes into production based on the assumption that this is a service is supposed to be shared between multiple projects since it stores locations

Issue reported by Ona.

**Comment by justinlewis** [comment]
Comments from @nmceachen - The number of Metadata Objects should be relatively small and probably not exceed several dozen, which is not a lot.

**Comment by rrowlands** [comment]
Agreed with @nmceachen. There appears to be a confusion in this ticket between data and metadata. The amount of data pulled will be large. The amount of metadata should be small and not cause issues.
