### ISSUE TITLE
Generate aar artifacts instead of jars

### ISSUE THREAD

**Issue by justinlewis** [terraframe/common-geo-registry-adapter#9]
We can use an aar artifact for the cgradapter-android instead of a jar, that’s the standard?

Issue reported by Ona

**Comment by justinlewis** [comment]
This was discussed and decided to put on low priority with the intent to be considered later if the need becomes more significant.

**Comment by rrowlands** [comment]
This issue is now fixed. We have done a release and the android library is now released as 0.3.0 as an aar.

You can download at:
http://nexus.terraframe.com/content/groups/public/com/cgr/adapter/cgradapter-android/0.3.0/cgradapter-android-0.3.0.aar
